# Auto-generated by Data Analytics AI Agent Runtime
import sys
import json
import base64
import io
import polars as pl
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats

DATASET_PATH = r"C:\Users\bilal_haider\OneDrive\Desktop\ai_agent_01\data\sample_sales_data.csv"
OUTPUT_JSON_PATH = r"C:\Users\bilal_haider\OneDrive\Desktop\ai_agent_01\.sandbox_runtime\result_b51f1175.json"

# Ensure output dictionary exists
__AGENT_OUTPUT__ = {
    "metrics": {},
    "base64_charts": [],
    "summary": ""
}

def save_current_figure_to_base64():
    buf = io.BytesIO()
    plt.tight_layout()
    plt.savefig(buf, format='png', dpi=150)
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode('utf-8')
    __AGENT_OUTPUT__["base64_charts"].append(b64)
    plt.close()



import polars as pl
import matplotlib.pyplot as plt

df = pl.read_csv(DATASET_PATH)

# Aggregation
cat_summary = (
    df.filter(pl.col("product_category").is_not_null())
    .group_by("product_category")
    .agg([
        pl.col("total_revenue").sum().alias("sum_revenue"),
        pl.col("units_sold").sum().alias("sum_units")
    ])
)

# Save metrics into output contract
__AGENT_OUTPUT__["metrics"] = {
    "total_revenue": float(df["total_revenue"].sum()),
    "avg_rating": float(df["customer_rating"].mean()),
    "category_counts": dict(zip(cat_summary["product_category"].to_list(), cat_summary["sum_revenue"].to_list()))
}

# Plot
plt.figure(figsize=(6, 4))
plt.bar(cat_summary["product_category"].to_list(), cat_summary["sum_revenue"].to_list(), color="royalblue")
plt.title("Revenue by Category")
plt.xlabel("Category")
plt.ylabel("Revenue ($)")
plt.xticks(rotation=45)
save_current_figure_to_base64()


# Write execution result contract
with open(OUTPUT_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(__AGENT_OUTPUT__, f, indent=2, default=str)
