# Auto-generated by Data Analytics AI Agent Runtime
import sys
import json
import base64
import io
import polars as pl
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats

DATASET_PATH = r"C:\Users\bilal_haider\OneDrive\Desktop\ai_agent_01\data\sample_sales_data.csv"
OUTPUT_JSON_PATH = r"C:\Users\bilal_haider\OneDrive\Desktop\ai_agent_01\.sandbox_runtime\result_8a7ed937.json"

# Ensure output dictionary exists
__AGENT_OUTPUT__ = {
    "metrics": {},
    "base64_charts": [],
    "summary": ""
}

def save_current_figure_to_base64():
    buf = io.BytesIO()
    plt.tight_layout()
    plt.savefig(buf, format='png', dpi=150)
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode('utf-8')
    __AGENT_OUTPUT__["base64_charts"].append(b64)
    plt.close()


import polars as pl
import matplotlib.pyplot as plt
from scipy import stats

# Read dataset using Polars
df = pl.read_csv(DATASET_PATH)

# Clean and filter null values
valid_df = df.filter(pl.col("product_category").is_not_null() & pl.col("total_revenue").is_not_null())

# Group-by category aggregations
category_summary = (
    valid_df.group_by("product_category")
    .agg([
        pl.col("total_revenue").sum().alias("total_revenue"),
        pl.col("total_revenue").mean().alias("avg_revenue"),
        pl.col("customer_rating").mean().alias("avg_rating"),
        pl.col("units_sold").sum().alias("total_units")
    ])
    .sort("total_revenue", descending=True)
)

# Statistical Correlation using SciPy (Rating vs Revenue)
corr_coef, p_value = stats.pearsonr(
    valid_df["customer_rating"].to_numpy(),
    valid_df["total_revenue"].to_numpy()
)

# Return rate calculation
returns_count = df.filter(pl.col("returned") == "Yes").height
return_rate = (returns_count / df.height) * 100

# Populate metrics output contract
__AGENT_OUTPUT__["metrics"] = {
    "overall_total_revenue": float(valid_df["total_revenue"].sum()),
    "avg_customer_rating": round(float(valid_df["customer_rating"].mean()), 2),
    "pearson_correlation_rating_vs_revenue": round(float(corr_coef), 4),
    "correlation_p_value": round(float(p_value), 6),
    "overall_return_rate_pct": round(float(return_rate), 2),
    "top_category": category_summary["product_category"][0],
    "category_revenue_distribution": dict(
        zip(category_summary["product_category"].to_list(), [round(x, 2) for x in category_summary["total_revenue"].to_list()])
    )
}

# Visualization 1: Total Revenue by Product Category
plt.figure(figsize=(8, 5))
categories = category_summary["product_category"].to_list()
revenues = category_summary["total_revenue"].to_list()
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
bars = plt.bar(categories, revenues, color=colors[:len(categories)], edgecolor='black', alpha=0.85)
plt.title("Total Revenue by Product Category", fontsize=14, fontweight='bold', pad=12)
plt.xlabel("Product Category", fontsize=11)
plt.ylabel("Total Revenue ($)", fontsize=11)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.xticks(rotation=25)
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 50, f"${yval:,.0f}", ha='center', va='bottom', fontsize=9)
save_current_figure_to_base64()

# Visualization 2: Customer Rating vs Revenue Scatter with Trendline
plt.figure(figsize=(8, 5))
ratings = valid_df["customer_rating"].to_numpy()
revs = valid_df["total_revenue"].to_numpy()
plt.scatter(ratings, revs, color='darkorange', edgecolors='black', s=70, alpha=0.8)
# Add linear regression fit line
slope, intercept, _, _, _ = stats.linregress(ratings, revs)
plt.plot(ratings, slope * ratings + intercept, color='navy', linestyle='--', linewidth=2, label=f"Trend (r = {corr_coef:.2f})")
plt.title("Customer Rating vs. Order Revenue", fontsize=14, fontweight='bold', pad=12)
plt.xlabel("Customer Rating (1 - 5 Stars)", fontsize=11)
plt.ylabel("Order Revenue ($)", fontsize=11)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
save_current_figure_to_base64()

__AGENT_OUTPUT__["summary"] = "Computed category revenue breakdown and Pearson correlation between ratings and order values."

# Write execution result contract
with open(OUTPUT_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(__AGENT_OUTPUT__, f, indent=2, default=str)
