# Auto-generated by Data Analytics AI Agent Runtime
import sys
import json
import base64
import io
import polars as pl
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats

DATASET_PATH = r"C:\Users\bilal_haider\OneDrive\Desktop\ai_agent_01\data\sample_sales_data.csv"
OUTPUT_JSON_PATH = r"C:\Users\bilal_haider\OneDrive\Desktop\ai_agent_01\.sandbox_runtime\result_4bb1ec4f.json"

# Ensure output dictionary exists
__AGENT_OUTPUT__ = {
    "metrics": {},
    "base64_charts": [],
    "summary": ""
}

def save_current_figure_to_base64():
    buf = io.BytesIO()
    plt.tight_layout()
    plt.savefig(buf, format='png', dpi=150)
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode('utf-8')
    __AGENT_OUTPUT__["base64_charts"].append(b64)
    plt.close()



import polars as pl
# Intentional bug: accessing non-existent column
df = pl.read_csv(DATASET_PATH)
invalid = df["non_existent_column_xyz"].sum()


# Write execution result contract
with open(OUTPUT_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(__AGENT_OUTPUT__, f, indent=2, default=str)
